language: node_js
node_js:
  - '8.12'

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - commitlint-travis
  - yarn prettify
  - ng lint
  - ng test --watch=false --no-progress
  - yarn coverage
  - yarn webdriver-update-ci
  - ng e2e --protractor-config=./e2e/protractor-ci.conf.js --webdriver-update=false
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/rabobank-test
